rio_grande_do_norte = Spree::State.find_by! abbr: 'RN'

Spree::City.create!([
  {state: rio_grande_do_norte, ibge_code: 2407104, name: "Macaíba"},
  {state: rio_grande_do_norte, ibge_code: 2408201, name: "Nísia Floresta"},
  {state: rio_grande_do_norte, ibge_code: 2412005, name: "São Gonçalo do Amarante"},
  {state: rio_grande_do_norte, ibge_code: 2403251, name: "Parnamirim"},
  {state: rio_grande_do_norte, ibge_code: 2403608, name: "Extremoz"},
  {state: rio_grande_do_norte, ibge_code: 2401206, name: "Arês"},
  {state: rio_grande_do_norte, ibge_code: 2401404, name: "Baía Formosa"},
  {state: rio_grande_do_norte, ibge_code: 2403509, name: "Espírito Santo"},
  {state: rio_grande_do_norte, ibge_code: 2404200, name: "Goianinha"},
  {state: rio_grande_do_norte, ibge_code: 2407708, name: "Montanhas"},
  {state: rio_grande_do_norte, ibge_code: 2409803, name: "Pedro Velho"},
  {state: rio_grande_do_norte, ibge_code: 2414209, name: "Tibau do Sul"},
  {state: rio_grande_do_norte, ibge_code: 2415008, name: "Vila Flor"},
  {state: rio_grande_do_norte, ibge_code: 2413706, name: "Sítio Novo"},
  {state: rio_grande_do_norte, ibge_code: 2404606, name: "Ielmo Marinho"},
  {state: rio_grande_do_norte, ibge_code: 2406601, name: "Lagoa Salgada"},
  {state: rio_grande_do_norte, ibge_code: 2409332, name: "Santa Maria"},
  {state: rio_grande_do_norte, ibge_code: 2412708, name: "São Pedro"},
  {state: rio_grande_do_norte, ibge_code: 2414803, name: "Vera Cruz"},
  {state: rio_grande_do_norte, ibge_code: 2410405, name: "Pureza"},
  {state: rio_grande_do_norte, ibge_code: 2402600, name: "Ceará-Mirim"},
  {state: rio_grande_do_norte, ibge_code: 2412203, name: "São José de Mipibu"},
  {state: rio_grande_do_norte, ibge_code: 2402204, name: "Canguaretama"},
  {state: rio_grande_do_norte, ibge_code: 2413201, name: "Senador Georgino Avelino"},
  {state: rio_grande_do_norte, ibge_code: 2405207, name: "Janduís"},
  {state: rio_grande_do_norte, ibge_code: 2411908, name: "São Francisco do Oeste"},
  {state: rio_grande_do_norte, ibge_code: 2411601, name: "São Bento do Norte"},
  {state: rio_grande_do_norte, ibge_code: 2405603, name: "Jardim de Piranhas"},
  {state: rio_grande_do_norte, ibge_code: 2408805, name: "Parazinho"},
  {state: rio_grande_do_norte, ibge_code: 2412302, name: "São José do Campestre"},
  {state: rio_grande_do_norte, ibge_code: 2414704, name: "Várzea"},
  {state: rio_grande_do_norte, ibge_code: 2408102, name: "Natal"},
  {state: rio_grande_do_norte, ibge_code: 2402303, name: "Caraúbas"},
  {state: rio_grande_do_norte, ibge_code: 2404853, name: "Itajá"},
  {state: rio_grande_do_norte, ibge_code: 2412500, name: "São Miguel"},
  {state: rio_grande_do_norte, ibge_code: 2411007, name: "Rodolfo Fernandes"},
  {state: rio_grande_do_norte, ibge_code: 2409704, name: "Pedro Avelino"},
  {state: rio_grande_do_norte, ibge_code: 2401651, name: "Bodó"},
  {state: rio_grande_do_norte, ibge_code: 2402709, name: "Cerro Corá"},
  {state: rio_grande_do_norte, ibge_code: 2403806, name: "Florânia"},
  {state: rio_grande_do_norte, ibge_code: 2406502, name: "Lagoa Nova"},
  {state: rio_grande_do_norte, ibge_code: 2411403, name: "Santana do Matos"},
  {state: rio_grande_do_norte, ibge_code: 2413003, name: "São Vicente"},
  {state: rio_grande_do_norte, ibge_code: 2414159, name: "Tenente Laurentino Cruz"},
  {state: rio_grande_do_norte, ibge_code: 2402006, name: "Caicó"},
  {state: rio_grande_do_norte, ibge_code: 2404804, name: "Ipueira"},
  {state: rio_grande_do_norte, ibge_code: 2411809, name: "São Fernando"},
  {state: rio_grande_do_norte, ibge_code: 2412104, name: "São João do Sabugi"},
  {state: rio_grande_do_norte, ibge_code: 2413409, name: "Serra Negra do Norte"},
  {state: rio_grande_do_norte, ibge_code: 2414308, name: "Timbaúba dos Batistas"},
  {state: rio_grande_do_norte, ibge_code: 2400109, name: "Acari"},
  {state: rio_grande_do_norte, ibge_code: 2402402, name: "Carnaúba dos Dantas"},
  {state: rio_grande_do_norte, ibge_code: 2403004, name: "Cruzeta"},
  {state: rio_grande_do_norte, ibge_code: 2403103, name: "Currais Novos"},
  {state: rio_grande_do_norte, ibge_code: 2403400, name: "Equador"},
  {state: rio_grande_do_norte, ibge_code: 2405702, name: "Jardim do Seridó"},
  {state: rio_grande_do_norte, ibge_code: 2408508, name: "Ouro Branco"},
  {state: rio_grande_do_norte, ibge_code: 2408904, name: "Parelhas"},
  {state: rio_grande_do_norte, ibge_code: 2411429, name: "Santana do Seridó"},
  {state: rio_grande_do_norte, ibge_code: 2412401, name: "São José do Seridó"},
  {state: rio_grande_do_norte, ibge_code: 2401602, name: "Bento Fernandes"},
  {state: rio_grande_do_norte, ibge_code: 2405108, name: "Jandaíra"},
  {state: rio_grande_do_norte, ibge_code: 2405801, name: "João Câmara"},
  {state: rio_grande_do_norte, ibge_code: 2410108, name: "Poço Branco"},
  {state: rio_grande_do_norte, ibge_code: 2401503, name: "Barcelona"},
  {state: rio_grande_do_norte, ibge_code: 2402105, name: "Campo Redondo"},
  {state: rio_grande_do_norte, ibge_code: 2402808, name: "Coronel Ezequiel"},
  {state: rio_grande_do_norte, ibge_code: 2405009, name: "Jaçanã"},
  {state: rio_grande_do_norte, ibge_code: 2405405, name: "Japi"},
  {state: rio_grande_do_norte, ibge_code: 2406403, name: "Lagoa de Velhos"},
  {state: rio_grande_do_norte, ibge_code: 2406809, name: "Lajes Pintadas"},
  {state: rio_grande_do_norte, ibge_code: 2407906, name: "Monte das Gameleiras"},
  {state: rio_grande_do_norte, ibge_code: 2411106, name: "Ruy Barbosa"},
  {state: rio_grande_do_norte, ibge_code: 2411205, name: "Santa Cruz"},
  {state: rio_grande_do_norte, ibge_code: 2411700, name: "São Bento do Trairí"},
  {state: rio_grande_do_norte, ibge_code: 2412906, name: "São Tomé"},
  {state: rio_grande_do_norte, ibge_code: 2413300, name: "Serra de São Bento"},
  {state: rio_grande_do_norte, ibge_code: 2414001, name: "Tangará"},
  {state: rio_grande_do_norte, ibge_code: 2401701, name: "Bom Jesus"},
  {state: rio_grande_do_norte, ibge_code: 2401800, name: "Brejinho"},
  {state: rio_grande_do_norte, ibge_code: 2405306, name: "Januário Cicco"},
  {state: rio_grande_do_norte, ibge_code: 2406155, name: "Jundiá"},
  {state: rio_grande_do_norte, ibge_code: 2406205, name: "Lagoa d'Anta"},
  {state: rio_grande_do_norte, ibge_code: 2406304, name: "Lagoa de Pedras"},
  {state: rio_grande_do_norte, ibge_code: 2407807, name: "Monte Alegre"},
  {state: rio_grande_do_norte, ibge_code: 2408300, name: "Nova Cruz"},
  {state: rio_grande_do_norte, ibge_code: 2409100, name: "Passa e Fica"},
  {state: rio_grande_do_norte, ibge_code: 2409209, name: "Passagem"},
  {state: rio_grande_do_norte, ibge_code: 2410306, name: "Presidente Juscelino"},
  {state: rio_grande_do_norte, ibge_code: 2410900, name: "Riachuelo"},
  {state: rio_grande_do_norte, ibge_code: 2411502, name: "Santo Antônio"},
  {state: rio_grande_do_norte, ibge_code: 2412609, name: "São Paulo do Potengi"},
  {state: rio_grande_do_norte, ibge_code: 2413102, name: "Senador Elói de Souza"},
  {state: rio_grande_do_norte, ibge_code: 2413508, name: "Serrinha"},
  {state: rio_grande_do_norte, ibge_code: 2407500, name: "Maxaranguape"},
  {state: rio_grande_do_norte, ibge_code: 2408953, name: "Rio do Fogo"},
  {state: rio_grande_do_norte, ibge_code: 2409506, name: "Pedra Grande"},
  {state: rio_grande_do_norte, ibge_code: 2412559, name: "São Miguel do Gostoso"},
  {state: rio_grande_do_norte, ibge_code: 2413904, name: "Taipu"},
  {state: rio_grande_do_norte, ibge_code: 2414407, name: "Touros"},
  {state: rio_grande_do_norte, ibge_code: 2413607, name: "Severiano Melo"},
  {state: rio_grande_do_norte, ibge_code: 2413805, name: "Taboleiro Grande"},
  {state: rio_grande_do_norte, ibge_code: 2414100, name: "Tenente Ananias"},
  {state: rio_grande_do_norte, ibge_code: 2414902, name: "Viçosa"},
  {state: rio_grande_do_norte, ibge_code: 2400604, name: "Almino Afonso"},
  {state: rio_grande_do_norte, ibge_code: 2400901, name: "Antônio Martins"},
  {state: rio_grande_do_norte, ibge_code: 2404002, name: "Frutuoso Gomes"},
  {state: rio_grande_do_norte, ibge_code: 2405900, name: "João Dias"},
  {state: rio_grande_do_norte, ibge_code: 2406908, name: "Lucrécia"},
  {state: rio_grande_do_norte, ibge_code: 2407401, name: "Martins"},
  {state: rio_grande_do_norte, ibge_code: 2408409, name: "Olho-d'Água do Borges"},
  {state: rio_grande_do_norte, ibge_code: 2409308, name: "Patu"},
  {state: rio_grande_do_norte, ibge_code: 2410603, name: "Rafael Godeiro"},
  {state: rio_grande_do_norte, ibge_code: 2413557, name: "Serrinha dos Pintos"},
  {state: rio_grande_do_norte, ibge_code: 2414506, name: "Umarizal"},
  {state: rio_grande_do_norte, ibge_code: 2401859, name: "Caiçara do Norte"},
  {state: rio_grande_do_norte, ibge_code: 2404101, name: "Galinhos"},
  {state: rio_grande_do_norte, ibge_code: 2404507, name: "Guamaré"},
  {state: rio_grande_do_norte, ibge_code: 2407203, name: "Macau"},
  {state: rio_grande_do_norte, ibge_code: 2400307, name: "Afonso Bezerra"},
  {state: rio_grande_do_norte, ibge_code: 2400802, name: "Angicos"},
  {state: rio_grande_do_norte, ibge_code: 2401909, name: "Caiçara do Rio do Vento"},
  {state: rio_grande_do_norte, ibge_code: 2403756, name: "Fernando Pedroza"},
  {state: rio_grande_do_norte, ibge_code: 2405504, name: "Jardim de Angicos"},
  {state: rio_grande_do_norte, ibge_code: 2406700, name: "Lajes"},
  {state: rio_grande_do_norte, ibge_code: 2409605, name: "Pedra Preta"},
  {state: rio_grande_do_norte, ibge_code: 2400703, name: "Alto do Rodrigues"},
  {state: rio_grande_do_norte, ibge_code: 2402501, name: "Carnaubais"},
  {state: rio_grande_do_norte, ibge_code: 2404705, name: "Ipanguaçu"},
  {state: rio_grande_do_norte, ibge_code: 2406106, name: "Jucurutu"},
  {state: rio_grande_do_norte, ibge_code: 2409902, name: "Pendências"},
  {state: rio_grande_do_norte, ibge_code: 2410256, name: "Porto do Mangue"},
  {state: rio_grande_do_norte, ibge_code: 2412807, name: "São Rafael"},
  {state: rio_grande_do_norte, ibge_code: 2400406, name: "Água Nova"},
  {state: rio_grande_do_norte, ibge_code: 2402907, name: "Coronel João Pessoa"},
  {state: rio_grande_do_norte, ibge_code: 2403202, name: "Doutor Severiano"},
  {state: rio_grande_do_norte, ibge_code: 2403301, name: "Encanto"},
  {state: rio_grande_do_norte, ibge_code: 2407005, name: "Luís Gomes"},
  {state: rio_grande_do_norte, ibge_code: 2407252, name: "Major Sales"},
  {state: rio_grande_do_norte, ibge_code: 2410801, name: "Riacho de Santana"},
  {state: rio_grande_do_norte, ibge_code: 2414753, name: "Venha-Ver"},
  {state: rio_grande_do_norte, ibge_code: 2400505, name: "Alexandria"},
  {state: rio_grande_do_norte, ibge_code: 2403905, name: "Francisco Dantas"},
  {state: rio_grande_do_norte, ibge_code: 2404903, name: "Itaú"},
  {state: rio_grande_do_norte, ibge_code: 2406007, name: "José da Penha"},
  {state: rio_grande_do_norte, ibge_code: 2407302, name: "Marcelino Vieira"},
  {state: rio_grande_do_norte, ibge_code: 2408607, name: "Paraná"},
  {state: rio_grande_do_norte, ibge_code: 2409407, name: "Pau dos Ferros"},
  {state: rio_grande_do_norte, ibge_code: 2410009, name: "Pilões"},
  {state: rio_grande_do_norte, ibge_code: 2410207, name: "Portalegre"},
  {state: rio_grande_do_norte, ibge_code: 2410504, name: "Rafael Fernandes"},
  {state: rio_grande_do_norte, ibge_code: 2410702, name: "Riacho da Cruz"},
  {state: rio_grande_do_norte, ibge_code: 2401107, name: "Areia Branca"},
  {state: rio_grande_do_norte, ibge_code: 2401453, name: "Baraúna"},
  {state: rio_grande_do_norte, ibge_code: 2404408, name: "Grossos"},
  {state: rio_grande_do_norte, ibge_code: 2408003, name: "Mossoró"},
  {state: rio_grande_do_norte, ibge_code: 2411056, name: "Tibau"},
  {state: rio_grande_do_norte, ibge_code: 2413359, name: "Serra do Mel"},
  {state: rio_grande_do_norte, ibge_code: 2401008, name: "Apodi"},
  {state: rio_grande_do_norte, ibge_code: 2403707, name: "Felipe Guerra"},
  {state: rio_grande_do_norte, ibge_code: 2404309, name: "Governador Dix-Sept Rosado"},
  {state: rio_grande_do_norte, ibge_code: 2401305, name: "Augusto Severo"},
  {state: rio_grande_do_norte, ibge_code: 2407609, name: "Messias Targino"},
  {state: rio_grande_do_norte, ibge_code: 2408706, name: "Paraú"},
  {state: rio_grande_do_norte, ibge_code: 2414456, name: "Triunfo Potiguar"},
  {state: rio_grande_do_norte, ibge_code: 2414605, name: "Upanema"},
  {state: rio_grande_do_norte, ibge_code: 2400208, name: "Açu"}
])