mato_grosso_do_sul = Spree::State.find_by! abbr: 'MS'

Spree::City.create!([
  {state: mato_grosso_do_sul, ibge_code: 5000856, name: "Angélica"},
  {state: mato_grosso_do_sul, ibge_code: 5003454, name: "Deodápolis"},
  {state: mato_grosso_do_sul, ibge_code: 5003751, name: "Eldorado"},
  {state: mato_grosso_do_sul, ibge_code: 5004007, name: "Glória de Dourados"},
  {state: mato_grosso_do_sul, ibge_code: 5004304, name: "Iguatemi"},
  {state: mato_grosso_do_sul, ibge_code: 5004700, name: "Ivinhema"},
  {state: mato_grosso_do_sul, ibge_code: 5004809, name: "Japorã"},
  {state: mato_grosso_do_sul, ibge_code: 5005103, name: "Jateí"},
  {state: mato_grosso_do_sul, ibge_code: 5006259, name: "Novo Horizonte do Sul"},
  {state: mato_grosso_do_sul, ibge_code: 5006358, name: "Paranhos"},
  {state: mato_grosso_do_sul, ibge_code: 5007703, name: "Sete Quedas"},
  {state: mato_grosso_do_sul, ibge_code: 5003207, name: "Corumbá"},
  {state: mato_grosso_do_sul, ibge_code: 5005202, name: "Ladário"},
  {state: mato_grosso_do_sul, ibge_code: 5006903, name: "Porto Murtinho"},
  {state: mato_grosso_do_sul, ibge_code: 5007695, name: "São Gabriel do Oeste"},
  {state: mato_grosso_do_sul, ibge_code: 5007208, name: "Rio Brilhante"},
  {state: mato_grosso_do_sul, ibge_code: 5002803, name: "Caracol"},
  {state: mato_grosso_do_sul, ibge_code: 5000609, name: "Amambaí"},
  {state: mato_grosso_do_sul, ibge_code: 5003504, name: "Douradina"},
  {state: mato_grosso_do_sul, ibge_code: 5005152, name: "Juti"},
  {state: mato_grosso_do_sul, ibge_code: 5006606, name: "Ponta Porã"},
  {state: mato_grosso_do_sul, ibge_code: 5003157, name: "Coronel Sapucaia"},
  {state: mato_grosso_do_sul, ibge_code: 5004601, name: "Itaquiraí"},
  {state: mato_grosso_do_sul, ibge_code: 5005707, name: "Naviraí"},
  {state: mato_grosso_do_sul, ibge_code: 5007950, name: "Tacuru"},
  {state: mato_grosso_do_sul, ibge_code: 5005608, name: "Miranda"},
  {state: mato_grosso_do_sul, ibge_code: 5004908, name: "Jaraguari"},
  {state: mato_grosso_do_sul, ibge_code: 5007109, name: "Ribas do Rio Pardo"},
  {state: mato_grosso_do_sul, ibge_code: 5003801, name: "Fátima do Sul"},
  {state: mato_grosso_do_sul, ibge_code: 5005681, name: "Mundo Novo"},
  {state: mato_grosso_do_sul, ibge_code: 5000708, name: "Anastácio"},
  {state: mato_grosso_do_sul, ibge_code: 5001102, name: "Aquidauana"},
  {state: mato_grosso_do_sul, ibge_code: 5003488, name: "Dois Irmãos do Buriti"},
  {state: mato_grosso_do_sul, ibge_code: 5000252, name: "Alcinópolis"},
  {state: mato_grosso_do_sul, ibge_code: 5002605, name: "Camapuã"},
  {state: mato_grosso_do_sul, ibge_code: 5003306, name: "Coxim"},
  {state: mato_grosso_do_sul, ibge_code: 5003900, name: "Figueirão"},
  {state: mato_grosso_do_sul, ibge_code: 5006408, name: "Pedro Gomes"},
  {state: mato_grosso_do_sul, ibge_code: 5007406, name: "Rio Verde de Mato Grosso"},
  {state: mato_grosso_do_sul, ibge_code: 5007935, name: "Sonora"},
  {state: mato_grosso_do_sul, ibge_code: 5001508, name: "Bandeirantes"},
  {state: mato_grosso_do_sul, ibge_code: 5002704, name: "Campo Grande"},
  {state: mato_grosso_do_sul, ibge_code: 5003108, name: "Corguinho"},
  {state: mato_grosso_do_sul, ibge_code: 5007307, name: "Rio Negro"},
  {state: mato_grosso_do_sul, ibge_code: 5007505, name: "Rochedo"},
  {state: mato_grosso_do_sul, ibge_code: 5007901, name: "Sidrolândia"},
  {state: mato_grosso_do_sul, ibge_code: 5008008, name: "Terenos"},
  {state: mato_grosso_do_sul, ibge_code: 5002902, name: "Cassilândia"},
  {state: mato_grosso_do_sul, ibge_code: 5002951, name: "Chapadão do Sul"},
  {state: mato_grosso_do_sul, ibge_code: 5003256, name: "Costa Rica"},
  {state: mato_grosso_do_sul, ibge_code: 5001003, name: "Aparecida do Taboado"},
  {state: mato_grosso_do_sul, ibge_code: 5004403, name: "Inocência"},
  {state: mato_grosso_do_sul, ibge_code: 5006309, name: "Paranaíba"},
  {state: mato_grosso_do_sul, ibge_code: 5007802, name: "Selvíria"},
  {state: mato_grosso_do_sul, ibge_code: 5000203, name: "Água Clara"},
  {state: mato_grosso_do_sul, ibge_code: 5002308, name: "Brasilândia"},
  {state: mato_grosso_do_sul, ibge_code: 5007554, name: "Santa Rita do Pardo"},
  {state: mato_grosso_do_sul, ibge_code: 5008305, name: "Três Lagoas"},
  {state: mato_grosso_do_sul, ibge_code: 5000807, name: "Anaurilândia"},
  {state: mato_grosso_do_sul, ibge_code: 5001904, name: "Bataguassu"},
  {state: mato_grosso_do_sul, ibge_code: 5002001, name: "Batayporã"},
  {state: mato_grosso_do_sul, ibge_code: 5006200, name: "Nova Andradina"},
  {state: mato_grosso_do_sul, ibge_code: 5007976, name: "Taquarussu"},
  {state: mato_grosso_do_sul, ibge_code: 5002100, name: "Bela Vista"},
  {state: mato_grosso_do_sul, ibge_code: 5002159, name: "Bodoquena"},
  {state: mato_grosso_do_sul, ibge_code: 5002209, name: "Bonito"},
  {state: mato_grosso_do_sul, ibge_code: 5004106, name: "Guia Lopes da Laguna"},
  {state: mato_grosso_do_sul, ibge_code: 5005004, name: "Jardim"},
  {state: mato_grosso_do_sul, ibge_code: 5005806, name: "Nioaque"},
  {state: mato_grosso_do_sul, ibge_code: 5000906, name: "Antônio João"},
  {state: mato_grosso_do_sul, ibge_code: 5001243, name: "Aral Moreira"},
  {state: mato_grosso_do_sul, ibge_code: 5002407, name: "Caarapó"},
  {state: mato_grosso_do_sul, ibge_code: 5003702, name: "Dourados"},
  {state: mato_grosso_do_sul, ibge_code: 5004502, name: "Itaporã"},
  {state: mato_grosso_do_sul, ibge_code: 5005251, name: "Laguna Carapã"},
  {state: mato_grosso_do_sul, ibge_code: 5005400, name: "Maracaju"},
  {state: mato_grosso_do_sul, ibge_code: 5006002, name: "Nova Alvorada do Sul"},
  {state: mato_grosso_do_sul, ibge_code: 5008404, name: "Vicentina"}
])