santa_catarina = Spree::State.find_by! abbr: 'SC'

Spree::City.create!([
    {state: santa_catarina, ibge_code: 4211876, name: "Paial"},
    {state: santa_catarina, ibge_code: 4212601, name: "Peritiba"},
    {state: santa_catarina, ibge_code: 4213104, name: "Piratuba"},
    {state: santa_catarina, ibge_code: 4213906, name: "Presidente Castello Branco"},
    {state: santa_catarina, ibge_code: 4217501, name: "Seara"},
    {state: santa_catarina, ibge_code: 4219606, name: "Xavantina"},
    {state: santa_catarina, ibge_code: 4203808, name: "Canoinhas"},
    {state: santa_catarina, ibge_code: 4200804, name: "Anchieta"},
    {state: santa_catarina, ibge_code: 4202081, name: "Bandeirante"},
    {state: santa_catarina, ibge_code: 4202156, name: "Belmonte"},
    {state: santa_catarina, ibge_code: 4205001, name: "Dionísio Cerqueira"},
    {state: santa_catarina, ibge_code: 4206405, name: "Guaraciaba"},
    {state: santa_catarina, ibge_code: 4208401, name: "Itapiranga"},
    {state: santa_catarina, ibge_code: 4211009, name: "Mondaí"},
    {state: santa_catarina, ibge_code: 4212007, name: "Palma Sola"},
    {state: santa_catarina, ibge_code: 4212239, name: "Paraíso"},
    {state: santa_catarina, ibge_code: 4215075, name: "Riqueza"},
    {state: santa_catarina, ibge_code: 4215208, name: "Romelândia"},
    {state: santa_catarina, ibge_code: 4215554, name: "Santa Helena"},
    {state: santa_catarina, ibge_code: 4216701, name: "São José do Cedro"},
    {state: santa_catarina, ibge_code: 4217204, name: "São Miguel do Oeste"},
    {state: santa_catarina, ibge_code: 4218756, name: "Tunápolis"},
    {state: santa_catarina, ibge_code: 4202578, name: "Bom Jesus do Oeste"},
    {state: santa_catarina, ibge_code: 4203105, name: "Caibi"},
    {state: santa_catarina, ibge_code: 4203501, name: "Campo Erê"},
    {state: santa_catarina, ibge_code: 4204103, name: "Caxambu do Sul"},
    {state: santa_catarina, ibge_code: 4204350, name: "Cordilheira Alta"},
    {state: santa_catarina, ibge_code: 4204400, name: "Coronel Freitas"},
    {state: santa_catarina, ibge_code: 4204707, name: "Cunha Porã"},
    {state: santa_catarina, ibge_code: 4205357, name: "Flor do Sertão"},
    {state: santa_catarina, ibge_code: 4205431, name: "Formosa do Sul"},
    {state: santa_catarina, ibge_code: 4206652, name: "Guatambú"},
    {state: santa_catarina, ibge_code: 4207858, name: "Irati"},
    {state: santa_catarina, ibge_code: 4208955, name: "Jardinópolis"},
    {state: santa_catarina, ibge_code: 4210506, name: "Maravilha"},
    {state: santa_catarina, ibge_code: 4211405, name: "Nova Erechim"},
    {state: santa_catarina, ibge_code: 4211454, name: "Nova Itaberaba"},
    {state: santa_catarina, ibge_code: 4205159, name: "Doutor Pedrinho"},
    {state: santa_catarina, ibge_code: 4205902, name: "Gaspar"},
    {state: santa_catarina, ibge_code: 4207502, name: "Indaial"},
    {state: santa_catarina, ibge_code: 4210001, name: "Luiz Alves"},
    {state: santa_catarina, ibge_code: 4213203, name: "Pomerode"},
    {state: santa_catarina, ibge_code: 4215109, name: "Rodeio"},
    {state: santa_catarina, ibge_code: 4202008, name: "Balneário Camboriú"},
    {state: santa_catarina, ibge_code: 4211652, name: "Novo Horizonte"},
    {state: santa_catarina, ibge_code: 4213153, name: "Planalto Alegre"},
    {state: santa_catarina, ibge_code: 4214201, name: "Quilombo"},
    {state: santa_catarina, ibge_code: 4215687, name: "Santa Terezinha do Progresso"},
    {state: santa_catarina, ibge_code: 4215695, name: "Santiago do Sul"},
    {state: santa_catarina, ibge_code: 4215752, name: "São Bernardino"},
    {state: santa_catarina, ibge_code: 4216909, name: "São Lourenço do Oeste"},
    {state: santa_catarina, ibge_code: 4217303, name: "Saudades"},
    {state: santa_catarina, ibge_code: 4217758, name: "Sul Brasil"},
    {state: santa_catarina, ibge_code: 4217956, name: "Tigrinhos"},
    {state: santa_catarina, ibge_code: 4218855, name: "União do Oeste"},
    {state: santa_catarina, ibge_code: 4202537, name: "Bom Jesus"},
    {state: santa_catarina, ibge_code: 4204459, name: "Coronel Martins"},
    {state: santa_catarina, ibge_code: 4205175, name: "Entre Rios"},
    {state: santa_catarina, ibge_code: 4205605, name: "Galvão"},
    {state: santa_catarina, ibge_code: 4207684, name: "Ipuaçu"},
    {state: santa_catarina, ibge_code: 4209177, name: "Jupiá"},
    {state: santa_catarina, ibge_code: 4209458, name: "Lajeado Grande"},
    {state: santa_catarina, ibge_code: 4210555, name: "Marema"},
    {state: santa_catarina, ibge_code: 4211850, name: "Ouro Verde"},
    {state: santa_catarina, ibge_code: 4212270, name: "Passos Maia"},
    {state: santa_catarina, ibge_code: 4213401, name: "Ponte Serrada"},
    {state: santa_catarina, ibge_code: 4219101, name: "Vargeão"},
    {state: santa_catarina, ibge_code: 4219507, name: "Xanxerê"},
    {state: santa_catarina, ibge_code: 4219705, name: "Xaxim"},
    {state: santa_catarina, ibge_code: 4200408, name: "Água Doce"},
    {state: santa_catarina, ibge_code: 4201604, name: "Arroio Trinta"},
    {state: santa_catarina, ibge_code: 4203006, name: "Caçador"},
    {state: santa_catarina, ibge_code: 4203154, name: "Calmon"},
    {state: santa_catarina, ibge_code: 4203907, name: "Capinzal"},
    {state: santa_catarina, ibge_code: 4204004, name: "Catanduvas"},
    {state: santa_catarina, ibge_code: 4205209, name: "Erval Velho"},
    {state: santa_catarina, ibge_code: 4205506, name: "Fraiburgo"},
    {state: santa_catarina, ibge_code: 4206702, name: "Herval d'Oeste"},
    {state: santa_catarina, ibge_code: 4206751, name: "Ibiam"},
    {state: santa_catarina, ibge_code: 4206801, name: "Ibicaré"},
    {state: santa_catarina, ibge_code: 4208609, name: "Jaborá"},
    {state: santa_catarina, ibge_code: 4209003, name: "Joaçaba"},
    {state: santa_catarina, ibge_code: 4209201, name: "Lacerdópolis"},
    {state: santa_catarina, ibge_code: 4209706, name: "Lebon Régis"},
    {state: santa_catarina, ibge_code: 4210035, name: "Luzerna"},
    {state: santa_catarina, ibge_code: 4210050, name: "Macieira"},
    {state: santa_catarina, ibge_code: 4210704, name: "Matos Costa"},
    {state: santa_catarina, ibge_code: 4211801, name: "Ouro"},
    {state: santa_catarina, ibge_code: 4213005, name: "Pinheiro Preto"},
    {state: santa_catarina, ibge_code: 4214409, name: "Rio das Antas"},
    {state: santa_catarina, ibge_code: 4215406, name: "Salto Veloso"},
    {state: santa_catarina, ibge_code: 4218509, name: "Treze Tílias"},
    {state: santa_catarina, ibge_code: 4219176, name: "Vargem Bonita"},
    {state: santa_catarina, ibge_code: 4219309, name: "Videira"},
    {state: santa_catarina, ibge_code: 4201273, name: "Arabutã"},
    {state: santa_catarina, ibge_code: 4201653, name: "Arvoredo"},
    {state: santa_catarina, ibge_code: 4204301, name: "Concórdia"},
    {state: santa_catarina, ibge_code: 4207601, name: "Ipira"},
    {state: santa_catarina, ibge_code: 4207700, name: "Ipumirim"},
    {state: santa_catarina, ibge_code: 4207809, name: "Irani"},
    {state: santa_catarina, ibge_code: 4208005, name: "Itá"},
    {state: santa_catarina, ibge_code: 4210407, name: "Maracajá"},
    {state: santa_catarina, ibge_code: 4210803, name: "Meleiro"},
    {state: santa_catarina, ibge_code: 4211256, name: "Morro Grande"},
    {state: santa_catarina, ibge_code: 4213807, name: "Praia Grande"},
    {state: santa_catarina, ibge_code: 4215653, name: "Santa Rosa do Sul"},
    {state: santa_catarina, ibge_code: 4216404, name: "São João do Sul"},
    {state: santa_catarina, ibge_code: 4218806, name: "Turvo"},
    {state: santa_catarina, ibge_code: 4207908, name: "Irineópolis"},
    {state: santa_catarina, ibge_code: 4208104, name: "Itaiópolis"},
    {state: santa_catarina, ibge_code: 4210100, name: "Mafra"},
    {state: santa_catarina, ibge_code: 4210308, name: "Major Vieira"},
    {state: santa_catarina, ibge_code: 4212205, name: "Papanduva"},
    {state: santa_catarina, ibge_code: 4213609, name: "Porto União"},
    {state: santa_catarina, ibge_code: 4215679, name: "Santa Terezinha"},
    {state: santa_catarina, ibge_code: 4218251, name: "Timbó Grande"},
    {state: santa_catarina, ibge_code: 4215000, name: "Rio Negrinho"},
    {state: santa_catarina, ibge_code: 4215802, name: "São Bento do Sul"},
    {state: santa_catarina, ibge_code: 4202057, name: "Balneário Barra do Sul"},
    {state: santa_catarina, ibge_code: 4204509, name: "Corupá"},
    {state: santa_catarina, ibge_code: 4205803, name: "Garuva"},
    {state: santa_catarina, ibge_code: 4208450, name: "Itapoá"},
    {state: santa_catarina, ibge_code: 4208906, name: "Jaraguá do Sul"},
    {state: santa_catarina, ibge_code: 4209102, name: "Joinville"},
    {state: santa_catarina, ibge_code: 4210605, name: "Massaranduba"},
    {state: santa_catarina, ibge_code: 4217402, name: "Schroeder"},
    {state: santa_catarina, ibge_code: 4200051, name: "Abdon Batista"},
    {state: santa_catarina, ibge_code: 4202875, name: "Brunópolis"},
    {state: santa_catarina, ibge_code: 4204806, name: "Curitibanos"},
    {state: santa_catarina, ibge_code: 4213302, name: "Ponte Alta"},
    {state: santa_catarina, ibge_code: 4213351, name: "Ponte Alta do Norte"},
    {state: santa_catarina, ibge_code: 4216057, name: "São Cristovão do Sul"},
    {state: santa_catarina, ibge_code: 4219150, name: "Vargem"},
    {state: santa_catarina, ibge_code: 4219853, name: "Zortéa"},
    {state: santa_catarina, ibge_code: 4201000, name: "Anita Garibaldi"},
    {state: santa_catarina, ibge_code: 4202503, name: "Bom Jardim da Serra"},
    {state: santa_catarina, ibge_code: 4202602, name: "Bom Retiro"},
    {state: santa_catarina, ibge_code: 4203253, name: "Capão Alto"},
    {state: santa_catarina, ibge_code: 4203402, name: "Campo Belo do Sul"},
    {state: santa_catarina, ibge_code: 4204178, name: "Cerro Negro"},
    {state: santa_catarina, ibge_code: 4204558, name: "Correia Pinto"},
    {state: santa_catarina, ibge_code: 4209300, name: "Lages"},
    {state: santa_catarina, ibge_code: 4211751, name: "Otacílio Costa"},
    {state: santa_catarina, ibge_code: 4215059, name: "Rio Rufino"},
    {state: santa_catarina, ibge_code: 4216503, name: "São Joaquim"},
    {state: santa_catarina, ibge_code: 4218905, name: "Urubici"},
    {state: santa_catarina, ibge_code: 4218954, name: "Urupema"},
    {state: santa_catarina, ibge_code: 4200309, name: "Agronômica"},
    {state: santa_catarina, ibge_code: 4201901, name: "Aurora"},
    {state: santa_catarina, ibge_code: 4202859, name: "Braço do Trombudo"},
    {state: santa_catarina, ibge_code: 4206900, name: "Ibirama"},
    {state: santa_catarina, ibge_code: 4209151, name: "José Boiteux"},
    {state: santa_catarina, ibge_code: 4209508, name: "Laurentino"},
    {state: santa_catarina, ibge_code: 4210852, name: "Mirim Doce"},
    {state: santa_catarina, ibge_code: 4213708, name: "Pouso Redondo"},
    {state: santa_catarina, ibge_code: 4214508, name: "Rio do Campo"},
    {state: santa_catarina, ibge_code: 4214607, name: "Rio do Oeste"},
    {state: santa_catarina, ibge_code: 4215307, name: "Salete"},
    {state: santa_catarina, ibge_code: 4218608, name: "Trombudo Central"},
    {state: santa_catarina, ibge_code: 4219358, name: "Vitor Meireles"},
    {state: santa_catarina, ibge_code: 4201257, name: "Apiúna"},
    {state: santa_catarina, ibge_code: 4201703, name: "Ascurra"},
    {state: santa_catarina, ibge_code: 4202206, name: "Benedito Novo"},
    {state: santa_catarina, ibge_code: 4202404, name: "Blumenau"},
    {state: santa_catarina, ibge_code: 4202909, name: "Brusque"},
    {state: santa_catarina, ibge_code: 4207759, name: "Iraceminha"},
    {state: santa_catarina, ibge_code: 4210902, name: "Modelo"},
    {state: santa_catarina, ibge_code: 4212106, name: "Palmitos"},
    {state: santa_catarina, ibge_code: 4215356, name: "Saltinho"},
    {state: santa_catarina, ibge_code: 4216008, name: "São Carlos"},
    {state: santa_catarina, ibge_code: 4217550, name: "Serra Alta"},
    {state: santa_catarina, ibge_code: 4200101, name: "Abelardo Luz"},
    {state: santa_catarina, ibge_code: 4202131, name: "Bela Vista do Toldo"},
    {state: santa_catarina, ibge_code: 4211108, name: "Monte Castelo"},
    {state: santa_catarina, ibge_code: 4218301, name: "Três Barras"},
    {state: santa_catarina, ibge_code: 4201307, name: "Araquari"},
    {state: santa_catarina, ibge_code: 4206504, name: "Guaramirim"},
    {state: santa_catarina, ibge_code: 4216206, name: "São Francisco do Sul"},
    {state: santa_catarina, ibge_code: 4202107, name: "Barra Velha"},
    {state: santa_catarina, ibge_code: 4203204, name: "Camboriú"},
    {state: santa_catarina, ibge_code: 4207106, name: "Ilhota"},
    {state: santa_catarina, ibge_code: 4208203, name: "Itajaí"},
    {state: santa_catarina, ibge_code: 4211306, name: "Navegantes"},
    {state: santa_catarina, ibge_code: 4212502, name: "Penha"},
    {state: santa_catarina, ibge_code: 4212809, name: "Balneário Piçarras"},
    {state: santa_catarina, ibge_code: 4216354, name: "São João do Itaperiú"},
    {state: santa_catarina, ibge_code: 4200200, name: "Agrolândia"},
    {state: santa_catarina, ibge_code: 4207403, name: "Imbuia"},
    {state: santa_catarina, ibge_code: 4208500, name: "Ituporanga"},
    {state: santa_catarina, ibge_code: 4212700, name: "Petrolândia"},
    {state: santa_catarina, ibge_code: 4219200, name: "Vidal Ramos"},
    {state: santa_catarina, ibge_code: 4203709, name: "Canelinha"},
    {state: santa_catarina, ibge_code: 4210209, name: "Major Gercino"},
    {state: santa_catarina, ibge_code: 4211504, name: "Nova Trento"},
    {state: santa_catarina, ibge_code: 4216305, name: "São João Batista"},
    {state: santa_catarina, ibge_code: 4201208, name: "Antônio Carlos"},
    {state: santa_catarina, ibge_code: 4202305, name: "Biguaçu"},
    {state: santa_catarina, ibge_code: 4205407, name: "Florianópolis"},
    {state: santa_catarina, ibge_code: 4212304, name: "Paulo Lopes"},
    {state: santa_catarina, ibge_code: 4215703, name: "Santo Amaro da Imperatriz"},
    {state: santa_catarina, ibge_code: 4216602, name: "São José"},
    {state: santa_catarina, ibge_code: 4217253, name: "São Pedro de Alcântara"},
    {state: santa_catarina, ibge_code: 4200606, name: "Águas Mornas"},
    {state: santa_catarina, ibge_code: 4201109, name: "Anitápolis"},
    {state: santa_catarina, ibge_code: 4214300, name: "Rancho Queimado"},
    {state: santa_catarina, ibge_code: 4215901, name: "São Bonifácio"},
    {state: santa_catarina, ibge_code: 4201505, name: "Armazém"},
    {state: santa_catarina, ibge_code: 4203956, name: "Capivari de Baixo"},
    {state: santa_catarina, ibge_code: 4205704, name: "Garopaba"},
    {state: santa_catarina, ibge_code: 4206207, name: "Gravatal"},
    {state: santa_catarina, ibge_code: 4207304, name: "Imbituba"},
    {state: santa_catarina, ibge_code: 4208807, name: "Jaguaruna"},
    {state: santa_catarina, ibge_code: 4209409, name: "Laguna"},
    {state: santa_catarina, ibge_code: 4212403, name: "Pedras Grandes"},
    {state: santa_catarina, ibge_code: 4214904, name: "Rio Fortuna"},
    {state: santa_catarina, ibge_code: 4215604, name: "Santa Rosa de Lima"},
    {state: santa_catarina, ibge_code: 4217006, name: "São Ludgero"},
    {state: santa_catarina, ibge_code: 4217105, name: "São Martinho"},
    {state: santa_catarina, ibge_code: 4204251, name: "Cocal do Sul"},
    {state: santa_catarina, ibge_code: 4204608, name: "Criciúma"},
    {state: santa_catarina, ibge_code: 4205456, name: "Forquilhinha"},
    {state: santa_catarina, ibge_code: 4211207, name: "Morro da Fumaça"},
    {state: santa_catarina, ibge_code: 4217600, name: "Siderópolis"},
    {state: santa_catarina, ibge_code: 4218350, name: "Treviso"},
    {state: santa_catarina, ibge_code: 4219002, name: "Urussanga"},
    {state: santa_catarina, ibge_code: 4201406, name: "Araranguá"},
    {state: santa_catarina, ibge_code: 4202073, name: "Balneário Gaivota"},
    {state: santa_catarina, ibge_code: 4205191, name: "Ermo"},
    {state: santa_catarina, ibge_code: 4208708, name: "Jacinto Machado"},
    {state: santa_catarina, ibge_code: 4200705, name: "Alfredo Wagner"},
    {state: santa_catarina, ibge_code: 4202800, name: "Braço do Norte"},
    {state: santa_catarina, ibge_code: 4207205, name: "Imaruí"},
    {state: santa_catarina, ibge_code: 4211702, name: "Orleans"},
    {state: santa_catarina, ibge_code: 4215455, name: "Sangão"},
    {state: santa_catarina, ibge_code: 4218400, name: "Treze de Maio"},
    {state: santa_catarina, ibge_code: 4207007, name: "Içara"},
    {state: santa_catarina, ibge_code: 4211603, name: "Nova Veneza"},
    {state: santa_catarina, ibge_code: 4201950, name: "Balneário Arroio do Silva"},
    {state: santa_catarina, ibge_code: 4212254, name: "Passo de Torres"},
    {state: santa_catarina, ibge_code: 4218103, name: "Timbé do Sul"},
    {state: santa_catarina, ibge_code: 4202099, name: "Barra Bonita"},
    {state: santa_catarina, ibge_code: 4200507, name: "Águas de Chapecó"},
    {state: santa_catarina, ibge_code: 4212908, name: "Pinhalzinho"},
    {state: santa_catarina, ibge_code: 4216107, name: "São Domingos"},
    {state: santa_catarina, ibge_code: 4207577, name: "Iomerê"},
    {state: santa_catarina, ibge_code: 4217907, name: "Tangará"},
    {state: santa_catarina, ibge_code: 4209854, name: "Lindóia do Sul"},
    {state: santa_catarina, ibge_code: 4203303, name: "Campo Alegre"},
    {state: santa_catarina, ibge_code: 4211058, name: "Monte Carlo"},
    {state: santa_catarina, ibge_code: 4212056, name: "Palmeira"},
    {state: santa_catarina, ibge_code: 4214003, name: "Presidente Getúlio"},
    {state: santa_catarina, ibge_code: 4218202, name: "Timbó"},
    {state: santa_catarina, ibge_code: 4201802, name: "Atalanta"},
    {state: santa_catarina, ibge_code: 4211900, name: "Palhoça"},
    {state: santa_catarina, ibge_code: 4206108, name: "Grão Pará"},
    {state: santa_catarina, ibge_code: 4209607, name: "Lauro Muller"},
    {state: santa_catarina, ibge_code: 4217709, name: "Sombrio"},
    {state: santa_catarina, ibge_code: 4205555, name: "Frei Rogério"},
    {state: santa_catarina, ibge_code: 4215505, name: "Santa Cecília"},
    {state: santa_catarina, ibge_code: 4202438, name: "Bocaina do Sul"},
    {state: santa_catarina, ibge_code: 4204152, name: "Celso Ramos"},
    {state: santa_catarina, ibge_code: 4211892, name: "Painel"},
    {state: santa_catarina, ibge_code: 4216800, name: "São José do Cerrito"},
    {state: santa_catarina, ibge_code: 4205100, name: "Dona Emma"},
    {state: santa_catarina, ibge_code: 4209904, name: "Lontras"},
    {state: santa_catarina, ibge_code: 4214102, name: "Presidente Nereu"},
    {state: santa_catarina, ibge_code: 4217808, name: "Taió"},
    {state: santa_catarina, ibge_code: 4219408, name: "Witmarsum"},
    {state: santa_catarina, ibge_code: 4202701, name: "Botuverá"},
    {state: santa_catarina, ibge_code: 4206306, name: "Guabiruba"},
    {state: santa_catarina, ibge_code: 4214706, name: "Rio dos Cedros"},
    {state: santa_catarina, ibge_code: 4202453, name: "Bombinhas"},
    {state: santa_catarina, ibge_code: 4208302, name: "Itapema"},
    {state: santa_catarina, ibge_code: 4213500, name: "Porto Belo"},
    {state: santa_catarina, ibge_code: 4204194, name: "Chapadão do Lageado"},
    {state: santa_catarina, ibge_code: 4209805, name: "Leoberto Leal"},
    {state: santa_catarina, ibge_code: 4218004, name: "Tijucas"},
    {state: santa_catarina, ibge_code: 4206009, name: "Governador Celso Ramos"},
    {state: santa_catarina, ibge_code: 4206603, name: "Guarujá do Sul"},
    {state: santa_catarina, ibge_code: 4217154, name: "São Miguel da Boa Vista"},
    {state: santa_catarina, ibge_code: 4205308, name: "Faxinal dos Guedes"},
    {state: santa_catarina, ibge_code: 4200754, name: "Alto Bela Vista"},
    {state: santa_catarina, ibge_code: 4203600, name: "Campos Novos"},
    {state: santa_catarina, ibge_code: 4214805, name: "Rio do Sul"},
    {state: santa_catarina, ibge_code: 4200903, name: "Angelina"},
    {state: santa_catarina, ibge_code: 4218707, name: "Tubarão"},
    {state: santa_catarina, ibge_code: 4204905, name: "Descanso"},
    {state: santa_catarina, ibge_code: 4207650, name: "Iporã do Oeste"},
    {state: santa_catarina, ibge_code: 4214151, name: "Princesa"},
    {state: santa_catarina, ibge_code: 4216255, name: "São João do Oeste"},
    {state: santa_catarina, ibge_code: 4200556, name: "Águas Frias"},
    {state: santa_catarina, ibge_code: 4204202, name: "Chapecó"},
    {state: santa_catarina, ibge_code: 4204756, name: "Cunhataí"}
])